import type { PlayerData } from "../store/gameStore";

type PlayerAttributes = PlayerData["attributes"];

export type WeightedAttribute = readonly [keyof PlayerAttributes, number];

export const POSITION_ATTRIBUTE_WEIGHTS: Record<string, readonly WeightedAttribute[]> = {
    Goalkeeper: [
        ["handling", 28],
        ["reflexes", 28],
        ["aerial", 14],
        ["positioning", 10],
        ["decisions", 10],
        ["composure", 5],
        ["strength", 5],
    ],
    RightBack: [
        ["pace", 18],
        ["stamina", 16],
        ["tackling", 17],
        ["defending", 16],
        ["positioning", 12],
        ["passing", 10],
        ["dribbling", 6],
        ["decisions", 5],
    ],
    LeftBack: [
        ["pace", 18],
        ["stamina", 16],
        ["tackling", 17],
        ["defending", 16],
        ["positioning", 12],
        ["passing", 10],
        ["dribbling", 6],
        ["decisions", 5],
    ],
    CenterBack: [
        ["defending", 24],
        ["tackling", 18],
        ["positioning", 18],
        ["strength", 14],
        ["aerial", 12],
        ["decisions", 8],
        ["composure", 6],
    ],
    RightWingBack: [
        ["pace", 18],
        ["stamina", 18],
        ["tackling", 14],
        ["defending", 12],
        ["passing", 13],
        ["dribbling", 11],
        ["vision", 7],
        ["decisions", 7],
    ],
    LeftWingBack: [
        ["pace", 18],
        ["stamina", 18],
        ["tackling", 14],
        ["defending", 12],
        ["passing", 13],
        ["dribbling", 11],
        ["vision", 7],
        ["decisions", 7],
    ],
    DefensiveMidfielder: [
        ["tackling", 18],
        ["positioning", 18],
        ["decisions", 16],
        ["passing", 14],
        ["defending", 12],
        ["stamina", 10],
        ["vision", 7],
        ["strength", 5],
    ],
    CentralMidfielder: [
        ["passing", 20],
        ["vision", 16],
        ["decisions", 16],
        ["stamina", 12],
        ["dribbling", 10],
        ["positioning", 9],
        ["teamwork", 9],
        ["tackling", 8],
    ],
    AttackingMidfielder: [
        ["vision", 20],
        ["passing", 18],
        ["dribbling", 16],
        ["decisions", 14],
        ["shooting", 10],
        ["positioning", 8],
        ["composure", 8],
        ["pace", 6],
    ],
    RightMidfielder: [
        ["pace", 17],
        ["stamina", 16],
        ["passing", 15],
        ["dribbling", 14],
        ["vision", 10],
        ["decisions", 10],
        ["positioning", 10],
        ["tackling", 8],
    ],
    LeftMidfielder: [
        ["pace", 17],
        ["stamina", 16],
        ["passing", 15],
        ["dribbling", 14],
        ["vision", 10],
        ["decisions", 10],
        ["positioning", 10],
        ["tackling", 8],
    ],
    RightWinger: [
        ["pace", 22],
        ["dribbling", 22],
        ["passing", 14],
        ["shooting", 12],
        ["vision", 10],
        ["decisions", 8],
        ["positioning", 6],
        ["stamina", 6],
    ],
    LeftWinger: [
        ["pace", 22],
        ["dribbling", 22],
        ["passing", 14],
        ["shooting", 12],
        ["vision", 10],
        ["decisions", 8],
        ["positioning", 6],
        ["stamina", 6],
    ],
    Striker: [
        ["shooting", 26],
        ["positioning", 18],
        ["decisions", 14],
        ["pace", 12],
        ["dribbling", 10],
        ["strength", 8],
        ["composure", 8],
        ["aerial", 4],
    ],
};

export const DEFAULT_ATTRIBUTE_WEIGHTS: readonly WeightedAttribute[] = [
    ["pace", 10],
    ["stamina", 10],
    ["strength", 10],
    ["passing", 10],
    ["shooting", 10],
    ["tackling", 10],
    ["dribbling", 10],
    ["defending", 10],
    ["positioning", 10],
    ["vision", 5],
    ["decisions", 5],
];

export const POSITION_CRITICAL_ATTRIBUTES: Record<
    string,
    readonly (keyof PlayerAttributes)[]
> = {
    Goalkeeper: ["handling", "reflexes", "positioning"],
    RightBack: ["tackling", "defending", "positioning"],
    LeftBack: ["tackling", "defending", "positioning"],
    CenterBack: ["defending", "tackling", "positioning"],
    RightWingBack: ["pace", "stamina", "tackling"],
    LeftWingBack: ["pace", "stamina", "tackling"],
    DefensiveMidfielder: ["tackling", "positioning", "passing"],
    CentralMidfielder: ["passing", "vision", "decisions"],
    AttackingMidfielder: ["vision", "passing", "dribbling"],
    RightMidfielder: ["pace", "passing", "stamina"],
    LeftMidfielder: ["pace", "passing", "stamina"],
    RightWinger: ["pace", "dribbling", "passing"],
    LeftWinger: ["pace", "dribbling", "passing"],
    Striker: ["shooting", "positioning", "decisions"],
};