import type {
  CompetitionDef,
  ConfederationDef,
  CountryDef,
  NamesDefinition,
  PlayerDef,
  StaffDef,
  TeamDef,
  WorldMetaDef,
} from "./types";

export interface SamplePackage {
  meta: WorldMetaDef;
  confederations: ConfederationDef[];
  countries: CountryDef[];
  teams: TeamDef[];
  players: PlayerDef[];
  staff?: StaffDef[];
  names: NamesDefinition;
  competitions: CompetitionDef[];
}

export const MINI_LEAGUE_SAMPLE: SamplePackage = {
  meta: {
    id: "northshire-mini-league",
    name: "Northshire Mini League",
    description:
      "A four-team example league for the Northshire region. Great starting point for learning the .ofm format.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "database",
    gameMinVersion: "0.3.0",
    baseYear: 2026,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: ["northshire-premier"],
    logo: null,
  },
  confederations: [{ id: "europe", name: "Europe" }],
  countries: [{ id: "ENG", name: "England", confederation: "europe" }],
  teams: [
    {
      id: "northshire-fc",
      name: "Northshire FC",
      shortName: "NSH",
      city: "Northshire",
      country: "ENG",
      colors: { primary: "#003366", secondary: "#ffffff" },
      playStyle: "Balanced",
      stadiumName: "Castle Park",
      reputationRange: [400, 650],
      financeRange: [800000, 3000000],
      logo: null,
      kitPattern: null,
      foundedYear: 1987,
    },
    {
      id: "westbrook-united",
      name: "Westbrook United",
      shortName: "WBU",
      city: "Westbrook",
      country: "ENG",
      colors: { primary: "#cc0000", secondary: "#ffffff" },
      playStyle: "Attacking",
      stadiumName: "Westbrook Arena",
      reputationRange: [350, 600],
      financeRange: [600000, 2500000],
      logo: null,
      kitPattern: null,
      foundedYear: 1996,
    },
    {
      id: "eastgate-city",
      name: "Eastgate City",
      shortName: "EGC",
      city: "Eastgate",
      country: "ENG",
      colors: { primary: "#0066cc", secondary: "#ffcc00" },
      playStyle: "HighPress",
      stadiumName: "City Ground",
      reputationRange: [300, 550],
      financeRange: [500000, 2000000],
      logo: null,
      kitPattern: null,
      foundedYear: 1991,
    },
    {
      id: "southfield-rovers",
      name: "Southfield Rovers",
      shortName: "SFR",
      city: "Southfield",
      country: "ENG",
      colors: { primary: "#006600", secondary: "#ffffff" },
      playStyle: "Defensive",
      stadiumName: "Rovers Stadium",
      reputationRange: [280, 500],
      financeRange: [400000, 1500000],
      logo: null,
      kitPattern: null,
      foundedYear: 1996,
    },
  ],
  players: [] as PlayerDef[],
  names: { version: 1, description: "", pools: {} },
  competitions: [
    {
      id: "northshire-premier",
      name: "Northshire Premier League",
      type: "League",
      scope: "Domestic",
      countryId: "ENG",
      priority: 10,
      format: { kind: "LeagueTable", legs: 2 },
      participants: {
        explicit: ["northshire-fc", "westbrook-united", "eastgate-city", "southfield-rovers"],
      },
      seasonStartMonth: 8,
      seasonStartDay: 1,
    },
  ],
};

export const IBERIA_MINI_SAMPLE: SamplePackage = {
  meta: {
    id: "iberia-mini-league",
    name: "Iberia Mini League",
    description: "Four fictional Iberian clubs in a two-legged domestic league — a good starting point for Spanish-style football.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "database",
    gameMinVersion: "0.3.0",
    baseYear: 2026,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: ["iberia-primera"],
    logo: null,
  },
  confederations: [{ id: "europe", name: "Europe" }],
  countries: [{ id: "ESP", name: "Spain", confederation: "europe" }],
  teams: [
    {
      id: "villa-del-sol",
      name: "Villa del Sol FC",
      shortName: "VDS",
      city: "Madrid",
      country: "ESP",
      colors: { primary: "#cc0000", secondary: "#ffd700" },
      playStyle: "Possession",
      stadiumName: "Estadio del Sol",
      reputationRange: [600, 850],
      financeRange: [2000000, 8000000],
      logo: null,
      kitPattern: null,
      foundedYear: 1978,
    },
    {
      id: "puerto-fc",
      name: "Puerto FC",
      shortName: "PFC",
      city: "Barcelona",
      country: "ESP",
      colors: { primary: "#003399", secondary: "#cc0000" },
      playStyle: "HighPress",
      stadiumName: "Camp Puerto",
      reputationRange: [550, 800],
      financeRange: [1500000, 6000000],
      logo: null,
      kitPattern: null,
      foundedYear: 1995,
    },
    {
      id: "real-camino",
      name: "Real Camino",
      shortName: "RCA",
      city: "Valencia",
      country: "ESP",
      colors: { primary: "#ff6600", secondary: "#000000" },
      playStyle: "Balanced",
      stadiumName: "Estadio Camino",
      reputationRange: [400, 650],
      financeRange: [800000, 3500000],
      logo: null,
      kitPattern: null,
      foundedYear: 1988,
    },
    {
      id: "atletico-sur",
      name: "Atlético Sur",
      shortName: "ATS",
      city: "Seville",
      country: "ESP",
      colors: { primary: "#cc0000", secondary: "#ffffff" },
      playStyle: "Defensive",
      stadiumName: "Estadio Sur",
      reputationRange: [350, 600],
      financeRange: [700000, 2500000],
      logo: null,
      kitPattern: null,
      foundedYear: 1976,
    },
  ],
  players: [] as PlayerDef[],
  names: { version: 1, description: "", pools: {} },
  competitions: [
    {
      id: "iberia-primera",
      name: "Iberia Primera División",
      type: "League",
      scope: "Domestic",
      countryId: "ESP",
      priority: 10,
      format: { kind: "LeagueTable", legs: 2 },
      participants: {
        explicit: ["villa-del-sol", "puerto-fc", "real-camino", "atletico-sur"],
      },
      seasonStartMonth: 8,
      seasonStartDay: 15,
    },
  ],
};

export const SOUTH_AMERICAN_CUP_SAMPLE: SamplePackage = {
  meta: {
    id: "copa-del-sur",
    name: "Copa del Sur",
    description: "Four fictional South American clubs from different countries competing in a continental knockout-group tournament.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "database",
    gameMinVersion: "0.3.0",
    baseYear: 2026,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: ["copa-del-sur"],
    logo: null,
  },
  confederations: [{ id: "south-america", name: "South America" }],
  countries: [
    { id: "ARG", name: "Argentina", confederation: "south-america" },
    { id: "BRA", name: "Brazil", confederation: "south-america" },
    { id: "URU", name: "Uruguay", confederation: "south-america" },
    { id: "CHL", name: "Chile", confederation: "south-america" },
  ],
  teams: [
    {
      id: "rio-grande-fc",
      name: "Rio Grande FC",
      shortName: "RGF",
      city: "Buenos Aires",
      country: "ARG",
      colors: { primary: "#74acdf", secondary: "#ffffff" },
      playStyle: "Attacking",
      stadiumName: "Estadio Grande",
      reputationRange: [500, 750],
      financeRange: [1000000, 4000000],
      logo: null,
      kitPattern: null,
      foundedYear: 1994,
    },
    {
      id: "copa-verde",
      name: "Copa Verde",
      shortName: "CPV",
      city: "Rio de Janeiro",
      country: "BRA",
      colors: { primary: "#009c3b", secondary: "#ffdf00" },
      playStyle: "HighPress",
      stadiumName: "Arena Verde",
      reputationRange: [480, 720],
      financeRange: [900000, 3500000],
      logo: null,
      kitPattern: null,
      foundedYear: 1989,
    },
    {
      id: "la-celeste-fc",
      name: "La Celeste FC",
      shortName: "LCF",
      city: "Montevideo",
      country: "URU",
      colors: { primary: "#75aadb", secondary: "#ffffff" },
      playStyle: "Balanced",
      stadiumName: "Estadio Celeste",
      reputationRange: [420, 680],
      financeRange: [700000, 2500000],
      logo: null,
      kitPattern: null,
      foundedYear: 1976,
    },
    {
      id: "la-roja-fc",
      name: "La Roja FC",
      shortName: "LRF",
      city: "Santiago",
      country: "CHL",
      colors: { primary: "#d52b1e", secondary: "#ffffff" },
      playStyle: "Defensive",
      stadiumName: "Estadio Roja",
      reputationRange: [380, 630],
      financeRange: [600000, 2000000],
      logo: null,
      kitPattern: null,
      foundedYear: 1985,
    },
  ],
  players: [] as PlayerDef[],
  names: { version: 1, description: "", pools: {} },
  competitions: [
    {
      id: "copa-del-sur",
      name: "Copa del Sur",
      type: "ContinentalClub",
      scope: "Continental",
      priority: 5,
      format: { kind: "GroupAndKnockout" },
      participants: {
        explicit: ["rio-grande-fc", "copa-verde", "la-celeste-fc", "la-roja-fc"],
      },
      seasonStartMonth: 2,
      seasonStartDay: 1,
    },
  ],
};

// Showcases the World Editor sections added for authored squads: a first team,
// an academy (youth) intake, backroom staff, and a country name pool — every
// piece you can fill in by hand, in one small database package.
export const ACADEMY_SHOWCASE_SAMPLE: SamplePackage = {
  meta: {
    id: "harbor-academy-showcase",
    name: "Harbor Academy Showcase",
    description:
      "One club authored end to end: first-team players, youth prospects, coaching staff, and a name pool. A reference for the World Editor's Players, Youth, Staff, and Names sections.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "database",
    gameMinVersion: "0.3.0",
    baseYear: 2026,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: ["harbor-league"],
    logo: null,
  },
  confederations: [{ id: "europe", name: "Europe" }],
  countries: [{ id: "ENG", name: "England", confederation: "europe" }],
  teams: [
    {
      id: "harbor-town-fc",
      name: "Harbor Town FC",
      shortName: "HTF",
      city: "Harbor Town",
      country: "ENG",
      colors: { primary: "#0d4f8b", secondary: "#f5c542" },
      playStyle: "Possession",
      stadiumName: "The Dockyard",
      reputationRange: [450, 700],
      financeRange: [900000, 3500000],
      logo: null,
      kitPattern: null,
      foundedYear: 1991,
    },
    {
      id: "rival-rovers",
      name: "Rival Rovers",
      shortName: "RRV",
      city: "Eastport",
      country: "ENG",
      colors: { primary: "#8b0d22", secondary: "#ffffff" },
      playStyle: "Counter",
      stadiumName: "Rover Park",
      reputationRange: [400, 650],
      financeRange: [700000, 2800000],
      logo: null,
      kitPattern: null,
      foundedYear: 1988,
    },
  ],
  players: [
    {
      id: "marcus-vane",
      name: "Marcus Vane",
      firstName: "Marcus",
      lastName: "Vane",
      club: "harbor-town-fc",
      nationality: "ENG",
      position: "Striker",
      footedness: "Right",
      dateOfBirth: "1996-04-12",
      overall: 78,
      potential: null,
      attributes: null,
    },
    {
      id: "elliot-shaw",
      name: "Elliot Shaw",
      firstName: "Elliot",
      lastName: "Shaw",
      club: "harbor-town-fc",
      nationality: "ENG",
      position: "CentralMidfielder",
      footedness: "Left",
      dateOfBirth: "1994-09-30",
      overall: 75,
      potential: null,
      attributes: null,
    },
    {
      id: "tom-reed",
      name: "Tom Reed",
      firstName: "Tom",
      lastName: "Reed",
      club: "harbor-town-fc",
      nationality: "ENG",
      position: "Goalkeeper",
      footedness: "Right",
      dateOfBirth: "1992-01-18",
      overall: 74,
      potential: null,
      attributes: null,
    },
    // Youth prospects — flagged youth: true so they join the academy squad.
    {
      id: "jamie-locke",
      name: "Jamie Locke",
      firstName: "Jamie",
      lastName: "Locke",
      club: "harbor-town-fc",
      nationality: "ENG",
      position: "AttackingMidfielder",
      footedness: "Both",
      dateOfBirth: "2009-06-02",
      overall: 58,
      // An authored ceiling: this is the prospect the academy sample exists to
      // show off, and without it his ceiling would be a random roll like any
      // other 16-year-old's.
      potential: 88,
      attributes: null,
      youth: true,
    },
    {
      id: "noah-finch",
      name: "Noah Finch",
      firstName: "Noah",
      lastName: "Finch",
      club: "harbor-town-fc",
      nationality: "ENG",
      position: "RightBack",
      footedness: "Right",
      dateOfBirth: "2010-02-21",
      overall: 55,
      potential: 72,
      attributes: null,
      youth: true,
    },
  ],
  staff: [
    {
      id: "diane-cole",
      firstName: "Diane",
      lastName: "Cole",
      club: "harbor-town-fc",
      nationality: "ENG",
      role: "AssistantManager",
      attributes: { coaching: 72, judgingAbility: 68, judgingPotential: 65, physiotherapy: 40 },
      specialization: null,
      dateOfBirth: "1974-03-15",
    },
    {
      id: "victor-pratt",
      firstName: "Victor",
      lastName: "Pratt",
      club: "harbor-town-fc",
      nationality: "ENG",
      role: "Coach",
      attributes: { coaching: 70, judgingAbility: 55, judgingPotential: 60, physiotherapy: 35 },
      specialization: "Youth",
      dateOfBirth: "1980-11-08",
    },
    {
      id: "amir-khan",
      firstName: "Amir",
      lastName: "Khan",
      club: "harbor-town-fc",
      nationality: "ENG",
      role: "Scout",
      attributes: { coaching: 45, judgingAbility: 78, judgingPotential: 80, physiotherapy: 30 },
      specialization: null,
      dateOfBirth: "1983-07-22",
    },
  ],
  names: {
    version: 1,
    description: "Sample English name pool",
    pools: {
      ENG: {
        first_names: ["Jack", "Harry", "Charlie", "Oscar", "George", "Alfie", "Freddie"],
        last_names: ["Walker", "Wright", "Hughes", "Carter", "Mason", "Barnes", "Knight"],
      },
    },
  },
  competitions: [
    {
      id: "harbor-league",
      name: "Harbor Regional League",
      type: "League",
      scope: "Domestic",
      countryId: "ENG",
      priority: 10,
      format: { kind: "LeagueTable", legs: 2 },
      participants: { explicit: ["harbor-town-fc", "rival-rovers"] },
      seasonStartMonth: 8,
      seasonStartDay: 1,
    },
  ],
};

// A names-only patch: no teams or competitions, just name pools for several
// countries. Demonstrates the "patch" package type and how name pools stack on
// top of a database world to enrich generated players.
export const NAME_PACK_SAMPLE: SamplePackage = {
  meta: {
    id: "global-name-pack",
    name: "Global Name Pack",
    description:
      "A patch package containing only name pools for several countries. Install it alongside a world to give generated players more varied, localized names.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "patch",
    gameMinVersion: "0.3.0",
    baseYear: null,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: [],
    logo: null,
  },
  confederations: [],
  countries: [],
  teams: [],
  players: [],
  staff: [],
  names: {
    version: 1,
    description: "Localized name pools for multiple countries",
    pools: {
      ES: {
        first_names: ["Hugo", "Mateo", "Lucas", "Martín", "Pablo", "Diego", "Álvaro"],
        last_names: ["García", "Martínez", "López", "Sánchez", "Romero", "Torres", "Navarro"],
      },
      DE: {
        first_names: ["Leon", "Finn", "Jonas", "Luca", "Felix", "Maximilian", "Paul"],
        last_names: ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Wagner", "Becker"],
      },
      BR: {
        first_names: ["Gabriel", "Lucas", "Matheus", "Rafael", "Bruno", "Thiago", "Felipe"],
        last_names: ["Silva", "Santos", "Oliveira", "Souza", "Costa", "Pereira", "Almeida"],
      },
    },
  },
  competitions: [],
};

// All bundled World Editor starter samples, in display order. Add new samples
// here and the home view picks them up automatically.
export const SAMPLE_PACKAGES: SamplePackage[] = [
  MINI_LEAGUE_SAMPLE,
  IBERIA_MINI_SAMPLE,
  SOUTH_AMERICAN_CUP_SAMPLE,
  ACADEMY_SHOWCASE_SAMPLE,
  NAME_PACK_SAMPLE,
];
