import type {
  CompetitionDef,
  ConfederationDef,
  CountryDef,
  NamesDefinition,
  PlayerDef,
  TeamDef,
  WorldMetaDef,
} from "./types";

export interface SamplePackage {
  meta: WorldMetaDef;
  confederations: ConfederationDef[];
  countries: CountryDef[];
  teams: TeamDef[];
  players: PlayerDef[];
  names: NamesDefinition;
  competitions: CompetitionDef[];
}

export const MINI_LEAGUE_SAMPLE: SamplePackage = {
  meta: {
    id: "northshire-mini-league",
    name: "Northshire Mini League",
    description:
      "A four-team example league for the Northshire region. Great starting point for learning the .ofm format.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "database",
    gameMinVersion: "0.3.0",
    baseYear: 2026,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: ["northshire-premier"],
  },
  confederations: [{ id: "europe", name: "Europe" }],
  countries: [{ id: "ENG", name: "England", confederation: "europe" }],
  teams: [
    {
      id: "northshire-fc",
      name: "Northshire FC",
      shortName: "NSH",
      city: "Northshire",
      country: "ENG",
      colors: { primary: "#003366", secondary: "#ffffff" },
      playStyle: "Balanced",
      stadiumName: "Castle Park",
      reputationRange: [400, 650],
      financeRange: [800000, 3000000],
      logo: null,
    },
    {
      id: "westbrook-united",
      name: "Westbrook United",
      shortName: "WBU",
      city: "Westbrook",
      country: "ENG",
      colors: { primary: "#cc0000", secondary: "#ffffff" },
      playStyle: "Attacking",
      stadiumName: "Westbrook Arena",
      reputationRange: [350, 600],
      financeRange: [600000, 2500000],
      logo: null,
    },
    {
      id: "eastgate-city",
      name: "Eastgate City",
      shortName: "EGC",
      city: "Eastgate",
      country: "ENG",
      colors: { primary: "#0066cc", secondary: "#ffcc00" },
      playStyle: "Pressing",
      stadiumName: "City Ground",
      reputationRange: [300, 550],
      financeRange: [500000, 2000000],
      logo: null,
    },
    {
      id: "southfield-rovers",
      name: "Southfield Rovers",
      shortName: "SFR",
      city: "Southfield",
      country: "ENG",
      colors: { primary: "#006600", secondary: "#ffffff" },
      playStyle: "Defensive",
      stadiumName: "Rovers Stadium",
      reputationRange: [280, 500],
      financeRange: [400000, 1500000],
      logo: null,
    },
  ],
  players: [] as PlayerDef[],
  names: { version: 1, description: "", pools: {} },
  competitions: [
    {
      id: "northshire-premier",
      name: "Northshire Premier League",
      type: "League",
      scope: "Domestic",
      countryId: "ENG",
      priority: 10,
      format: { kind: "LeagueTable", legs: 2 },
      participants: {
        explicit: ["northshire-fc", "westbrook-united", "eastgate-city", "southfield-rovers"],
      },
      seasonStartMonth: 8,
      seasonStartDay: 1,
    },
  ],
};

export const IBERIA_MINI_SAMPLE: SamplePackage = {
  meta: {
    id: "iberia-mini-league",
    name: "Iberia Mini League",
    description: "Four fictional Iberian clubs in a two-legged domestic league — a good starting point for Spanish-style football.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "database",
    gameMinVersion: "0.3.0",
    baseYear: 2026,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: ["iberia-primera"],
  },
  confederations: [{ id: "europe", name: "Europe" }],
  countries: [{ id: "ESP", name: "Spain", confederation: "europe" }],
  teams: [
    {
      id: "villa-del-sol",
      name: "Villa del Sol FC",
      shortName: "VDS",
      city: "Madrid",
      country: "ESP",
      colors: { primary: "#cc0000", secondary: "#ffd700" },
      playStyle: "Possession",
      stadiumName: "Estadio del Sol",
      reputationRange: [600, 850],
      financeRange: [2000000, 8000000],
      logo: null,
    },
    {
      id: "puerto-fc",
      name: "Puerto FC",
      shortName: "PFC",
      city: "Barcelona",
      country: "ESP",
      colors: { primary: "#003399", secondary: "#cc0000" },
      playStyle: "Pressing",
      stadiumName: "Camp Puerto",
      reputationRange: [550, 800],
      financeRange: [1500000, 6000000],
      logo: null,
    },
    {
      id: "real-camino",
      name: "Real Camino",
      shortName: "RCA",
      city: "Valencia",
      country: "ESP",
      colors: { primary: "#ff6600", secondary: "#000000" },
      playStyle: "Balanced",
      stadiumName: "Estadio Camino",
      reputationRange: [400, 650],
      financeRange: [800000, 3500000],
      logo: null,
    },
    {
      id: "atletico-sur",
      name: "Atlético Sur",
      shortName: "ATS",
      city: "Seville",
      country: "ESP",
      colors: { primary: "#cc0000", secondary: "#ffffff" },
      playStyle: "Defensive",
      stadiumName: "Estadio Sur",
      reputationRange: [350, 600],
      financeRange: [700000, 2500000],
      logo: null,
    },
  ],
  players: [] as PlayerDef[],
  names: { version: 1, description: "", pools: {} },
  competitions: [
    {
      id: "iberia-primera",
      name: "Iberia Primera División",
      type: "League",
      scope: "Domestic",
      countryId: "ESP",
      priority: 10,
      format: { kind: "LeagueTable", legs: 2 },
      participants: {
        explicit: ["villa-del-sol", "puerto-fc", "real-camino", "atletico-sur"],
      },
      seasonStartMonth: 8,
      seasonStartDay: 15,
    },
  ],
};

export const SOUTH_AMERICAN_CUP_SAMPLE: SamplePackage = {
  meta: {
    id: "copa-del-sur",
    name: "Copa del Sur",
    description: "Four fictional South American clubs from different countries competing in a continental knockout-group tournament.",
    version: "1.0.0",
    author: "",
    license: "CC0-1.0",
    packageType: "database",
    gameMinVersion: "0.3.0",
    baseYear: 2026,
    formatVersion: 1,
    defaultActiveRegions: [],
    defaultActiveCompetitions: ["copa-del-sur"],
  },
  confederations: [{ id: "south-america", name: "South America" }],
  countries: [
    { id: "ARG", name: "Argentina", confederation: "south-america" },
    { id: "BRA", name: "Brazil", confederation: "south-america" },
    { id: "URU", name: "Uruguay", confederation: "south-america" },
    { id: "CHL", name: "Chile", confederation: "south-america" },
  ],
  teams: [
    {
      id: "rio-grande-fc",
      name: "Rio Grande FC",
      shortName: "RGF",
      city: "Buenos Aires",
      country: "ARG",
      colors: { primary: "#74acdf", secondary: "#ffffff" },
      playStyle: "Attacking",
      stadiumName: "Estadio Grande",
      reputationRange: [500, 750],
      financeRange: [1000000, 4000000],
      logo: null,
    },
    {
      id: "copa-verde",
      name: "Copa Verde",
      shortName: "CPV",
      city: "Rio de Janeiro",
      country: "BRA",
      colors: { primary: "#009c3b", secondary: "#ffdf00" },
      playStyle: "Pressing",
      stadiumName: "Arena Verde",
      reputationRange: [480, 720],
      financeRange: [900000, 3500000],
      logo: null,
    },
    {
      id: "la-celeste-fc",
      name: "La Celeste FC",
      shortName: "LCF",
      city: "Montevideo",
      country: "URU",
      colors: { primary: "#75aadb", secondary: "#ffffff" },
      playStyle: "Balanced",
      stadiumName: "Estadio Celeste",
      reputationRange: [420, 680],
      financeRange: [700000, 2500000],
      logo: null,
    },
    {
      id: "la-roja-fc",
      name: "La Roja FC",
      shortName: "LRF",
      city: "Santiago",
      country: "CHL",
      colors: { primary: "#d52b1e", secondary: "#ffffff" },
      playStyle: "Defensive",
      stadiumName: "Estadio Roja",
      reputationRange: [380, 630],
      financeRange: [600000, 2000000],
      logo: null,
    },
  ],
  players: [] as PlayerDef[],
  names: { version: 1, description: "", pools: {} },
  competitions: [
    {
      id: "copa-del-sur",
      name: "Copa del Sur",
      type: "ContinentalClub",
      scope: "Continental",
      priority: 5,
      format: { kind: "GroupAndKnockout" },
      participants: {
        explicit: ["rio-grande-fc", "copa-verde", "la-celeste-fc", "la-roja-fc"],
      },
      seasonStartMonth: 2,
      seasonStartDay: 1,
    },
  ],
};
