// ---------------------------------------------------------------------------
// Nationality-aware name pools
// ---------------------------------------------------------------------------

pub(super) struct NationalityNames {
    pub nationality: &'static str,
    pub first_names: &'static [&'static str],
    pub last_names: &'static [&'static str],
}

pub(super) const NATIONALITY_POOLS: &[NationalityNames] = &[
    NationalityNames {
        nationality: "ENG",
        first_names: &[
            "James", "Harry", "Jack", "Oliver", "George", "Charlie", "Thomas", "William", "Daniel",
            "Ben", "Luke", "Ryan", "Sam", "Callum", "Nathan", "Adam", "Liam", "Marcus", "Ethan",
            "Mason",
        ],
        last_names: &[
            "Smith", "Johnson", "Brown", "Jones", "Taylor", "Wilson", "Walker", "Robinson",
            "Clark", "Wright", "Hall", "Green", "Baker", "Hill", "Allen", "Young", "King",
            "Cooper", "Parker", "Turner",
        ],
    },
    NationalityNames {
        nationality: "SCO",
        first_names: &[
            "Jack", "Lewis", "Fraser", "Ross", "Callum", "Scott", "Ryan", "Ewan", "Craig",
            "Stuart", "Cameron", "Kieran", "Jamie", "Gregor", "Finlay", "Liam", "Arran", "Declan",
            "Blair", "Dylan",
        ],
        last_names: &[
            "McDonald",
            "Stewart",
            "Robertson",
            "Campbell",
            "Anderson",
            "Scott",
            "Reid",
            "Murray",
            "Ross",
            "Paterson",
            "Ferguson",
            "MacLeod",
            "Johnston",
            "Morrison",
            "Walker",
            "Bell",
            "Fraser",
            "Clark",
            "Sutherland",
            "Graham",
        ],
    },
    NationalityNames {
        nationality: "WAL",
        first_names: &[
            "Rhys", "Dylan", "Owain", "Gethin", "Harri", "Cai", "Ioan", "Evan", "Morgan", "Ellis",
            "Tomos", "Aneurin", "Lloyd", "Osian", "Jac", "Ieuan", "Bryn", "Steffan", "Carwyn",
            "Gruffydd",
        ],
        last_names: &[
            "Jones",
            "Williams",
            "Davies",
            "Evans",
            "Thomas",
            "Roberts",
            "Lewis",
            "Morgan",
            "Griffiths",
            "Hughes",
            "Price",
            "Rees",
            "Jenkins",
            "Owen",
            "Lloyd",
            "Edwards",
            "Pritchard",
            "Powell",
            "Vaughan",
            "Parry",
        ],
    },
    NationalityNames {
        nationality: "NIR",
        first_names: &[
            "Conor", "Ryan", "Niall", "Ciaran", "Eoin", "Sean", "Darragh", "Ronan", "Cathal",
            "Paddy", "Shane", "Rory", "Callum", "Odhran", "Aidan", "Ethan", "Johnny", "Reece",
            "Aaron", "Daniel",
        ],
        last_names: &[
            "McCann",
            "O'Neill",
            "Murphy",
            "Doherty",
            "McLaughlin",
            "Quinn",
            "McKenna",
            "Gallagher",
            "Devlin",
            "Maguire",
            "Boyle",
            "McAllister",
            "McBride",
            "McCormick",
            "Campbell",
            "McGrath",
            "Mullan",
            "Morrow",
            "Moore",
            "Lavery",
        ],
    },
    NationalityNames {
        nationality: "IE",
        first_names: &[
            "Sean", "Conor", "Cian", "Darragh", "Oisin", "Padraig", "Tadhg", "Eoin", "Ronan",
            "Fionn", "Cillian", "Brian", "Aidan", "Shane", "Diarmuid", "Niall", "Ruairi", "Cathal",
            "Liam", "Jack",
        ],
        last_names: &[
            "Murphy",
            "Kelly",
            "Byrne",
            "Ryan",
            "O'Brien",
            "Walsh",
            "Doyle",
            "McCarthy",
            "Gallagher",
            "Kennedy",
            "Lynch",
            "Murray",
            "Quinn",
            "Moore",
            "Dunne",
            "Carroll",
            "Connolly",
            "Sullivan",
            "Brennan",
            "Power",
        ],
    },
    NationalityNames {
        nationality: "GB",
        first_names: &[
            "James", "Harry", "Jack", "Oliver", "George", "Charlie", "Thomas", "William", "Daniel",
            "Ben", "Luke", "Ryan", "Joe", "Sam", "Callum", "Nathan", "Ross", "Adam", "Liam",
            "Marcus",
        ],
        last_names: &[
            "Smith", "Johnson", "Williams", "Brown", "Jones", "Taylor", "Wilson", "Davies",
            "Evans", "Walker", "Robinson", "Clark", "Wright", "Hall", "Green", "Baker", "Hill",
            "Allen", "Young", "King",
        ],
    },
    NationalityNames {
        nationality: "ES",
        first_names: &[
            "Sergio",
            "Pablo",
            "Alejandro",
            "Carlos",
            "Javier",
            "Miguel",
            "Raul",
            "David",
            "Andres",
            "Alvaro",
            "Hugo",
            "Iker",
            "Marcos",
            "Luis",
            "Pedro",
            "Adrian",
            "Diego",
            "Fernando",
            "Gonzalo",
            "Antonio",
        ],
        last_names: &[
            "Garcia",
            "Rodriguez",
            "Martinez",
            "Lopez",
            "Sanchez",
            "Fernandez",
            "Gonzalez",
            "Hernandez",
            "Moreno",
            "Ruiz",
            "Diaz",
            "Alvarez",
            "Romero",
            "Torres",
            "Navarro",
            "Gil",
            "Vega",
            "Ramos",
            "Ortiz",
            "Castro",
        ],
    },
    NationalityNames {
        nationality: "DE",
        first_names: &[
            "Lukas",
            "Niklas",
            "Leon",
            "Felix",
            "Maximilian",
            "Jonas",
            "Florian",
            "Julian",
            "Tim",
            "Jan",
            "Kevin",
            "Marco",
            "Kai",
            "Stefan",
            "Patrick",
            "Dennis",
            "Tobias",
            "Marcel",
            "Timo",
            "Lars",
        ],
        last_names: &[
            "Müller",
            "Schmidt",
            "Schneider",
            "Fischer",
            "Weber",
            "Meyer",
            "Wagner",
            "Becker",
            "Schulz",
            "Hoffmann",
            "Koch",
            "Richter",
            "Wolf",
            "Schäfer",
            "Neumann",
            "Schwarz",
            "Zimmermann",
            "Braun",
            "Hartmann",
            "Krüger",
        ],
    },
    NationalityNames {
        nationality: "FR",
        first_names: &[
            "Antoine",
            "Hugo",
            "Lucas",
            "Mathieu",
            "Julien",
            "Maxime",
            "Pierre",
            "Thomas",
            "Raphael",
            "Adrien",
            "Kevin",
            "Alexandre",
            "Nicolas",
            "Loic",
            "Clement",
            "Florian",
            "Theo",
            "Damien",
            "Yann",
            "Baptiste",
        ],
        last_names: &[
            "Martin", "Bernard", "Dubois", "Thomas", "Robert", "Petit", "Moreau", "Laurent",
            "Simon", "Michel", "Lefevre", "Leroy", "Roux", "David", "Bertrand", "Morel",
            "Fournier", "Girard", "Bonnet", "Dupont",
        ],
    },
    NationalityNames {
        nationality: "IT",
        first_names: &[
            "Marco",
            "Luca",
            "Andrea",
            "Matteo",
            "Alessandro",
            "Lorenzo",
            "Davide",
            "Simone",
            "Riccardo",
            "Federico",
            "Gianluca",
            "Stefano",
            "Fabio",
            "Roberto",
            "Nicola",
            "Salvatore",
            "Daniele",
            "Paolo",
            "Vincenzo",
            "Emanuele",
        ],
        last_names: &[
            "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci",
            "Marino", "Greco", "Bruno", "Gallo", "Conti", "De Luca", "Costa", "Mancini",
            "Barbieri", "Fontana", "Santoro", "Rinaldi",
        ],
    },
    NationalityNames {
        nationality: "NL",
        first_names: &[
            "Daan", "Sem", "Lars", "Tim", "Thomas", "Jesse", "Jordi", "Luuk", "Rick", "Bas",
            "Stijn", "Nick", "Davy", "Wesley", "Kevin", "Robin", "Sander", "Ruud", "Dennis",
            "Patrick",
        ],
        last_names: &[
            "De Jong",
            "Van Dijk",
            "Jansen",
            "De Vries",
            "Van den Berg",
            "Bakker",
            "Visser",
            "Smit",
            "Meijer",
            "De Boer",
            "Mulder",
            "Dekker",
            "Peters",
            "Hendriks",
            "Van Leeuwen",
            "De Graaf",
            "Kok",
            "Brouwer",
            "Vermeer",
            "Van Dam",
        ],
    },
    NationalityNames {
        nationality: "PT",
        first_names: &[
            "Rui", "Joao", "Bruno", "Diogo", "Pedro", "Tiago", "Nuno", "Miguel", "Andre",
            "Goncalo", "Rafael", "Luis", "Ricardo", "Hugo", "Fabio", "Bernardo", "Daniel", "Vitor",
            "Nelson", "Sergio",
        ],
        last_names: &[
            "Silva",
            "Santos",
            "Ferreira",
            "Costa",
            "Pereira",
            "Oliveira",
            "Rodrigues",
            "Martins",
            "Sousa",
            "Fernandes",
            "Goncalves",
            "Lopes",
            "Almeida",
            "Carvalho",
            "Ribeiro",
            "Pinto",
            "Teixeira",
            "Mendes",
            "Neves",
            "Vieira",
        ],
    },
    NationalityNames {
        nationality: "BR",
        first_names: &[
            "Lucas",
            "Gabriel",
            "Rafael",
            "Matheus",
            "Guilherme",
            "Felipe",
            "Thiago",
            "Vinicius",
            "Pedro",
            "Gustavo",
            "Bruno",
            "Leonardo",
            "Anderson",
            "Douglas",
            "Eduardo",
            "Henrique",
            "Marcelo",
            "Diego",
            "Igor",
            "Leandro",
        ],
        last_names: &[
            "Silva",
            "Santos",
            "Oliveira",
            "Souza",
            "Pereira",
            "Costa",
            "Ferreira",
            "Rodrigues",
            "Almeida",
            "Nascimento",
            "Lima",
            "Araujo",
            "Ribeiro",
            "Carvalho",
            "Gomes",
            "Martins",
            "Rocha",
            "Mendes",
            "Barbosa",
            "Moreira",
        ],
    },
    NationalityNames {
        nationality: "AR",
        first_names: &[
            "Lionel", "Gonzalo", "Angel", "Sergio", "Nicolas", "Pablo", "Mauro", "Lucas",
            "Ezequiel", "Javier", "Marcos", "Leandro", "Federico", "Ignacio", "Rodrigo", "Matias",
            "Franco", "Agustin", "Julian", "Cristian",
        ],
        last_names: &[
            "Gonzalez",
            "Rodriguez",
            "Martinez",
            "Lopez",
            "Fernandez",
            "Garcia",
            "Romero",
            "Diaz",
            "Torres",
            "Sanchez",
            "Alvarez",
            "Acosta",
            "Gutierrez",
            "Castro",
            "Pereyra",
            "Aguero",
            "Ruiz",
            "Herrera",
            "Medina",
            "Flores",
        ],
    },
    NationalityNames {
        nationality: "BE",
        first_names: &[
            "Kevin", "Eden", "Romelu", "Dries", "Yannick", "Thomas", "Axel", "Thorgan", "Michy",
            "Nacer", "Radja", "Jan", "Toby", "Simon", "Leander", "Jason", "Timothy", "Hans",
            "Dennis", "Laurent",
        ],
        last_names: &[
            "Janssens", "Peeters", "Maes", "Jacobs", "Mertens", "Willems", "Claes", "Goossens",
            "Wouters", "De Smet", "Hermans", "Peters", "Stevens", "Leclercq", "Lambert", "Dupont",
            "Dumont", "Simon", "Laurent", "Renard",
        ],
    },
    NationalityNames {
        nationality: "HR",
        first_names: &[
            "Luka", "Ivan", "Mateo", "Mario", "Dejan", "Ante", "Josip", "Marko", "Nikola",
            "Marcelo", "Andrej", "Darijo", "Sime", "Borna", "Domagoj", "Vedran", "Duje", "Filip",
            "Tin", "Bruno",
        ],
        last_names: &[
            "Kovacic",
            "Horvat",
            "Babic",
            "Maric",
            "Juric",
            "Novak",
            "Perisic",
            "Tomic",
            "Vucinic",
            "Brozovic",
            "Kramaric",
            "Vidovic",
            "Lovren",
            "Srna",
            "Rakitic",
            "Modric",
            "Pasalic",
            "Rebic",
            "Livakovic",
            "Gvardiol",
        ],
    },
    NationalityNames {
        nationality: "SE",
        first_names: &[
            "Emil",
            "Oscar",
            "Viktor",
            "Erik",
            "Alexander",
            "Marcus",
            "Sebastian",
            "Filip",
            "Albin",
            "Robin",
            "Pontus",
            "Mattias",
            "Andreas",
            "Gustav",
            "Kristoffer",
            "Joel",
            "Ludwig",
            "Simon",
            "Martin",
            "Henrik",
        ],
        last_names: &[
            "Andersson",
            "Johansson",
            "Karlsson",
            "Nilsson",
            "Eriksson",
            "Larsson",
            "Olsson",
            "Persson",
            "Svensson",
            "Gustafsson",
            "Pettersson",
            "Jonsson",
            "Jansson",
            "Hansson",
            "Bengtsson",
            "Lindberg",
            "Lundqvist",
            "Forsberg",
            "Lindqvist",
            "Berg",
        ],
    },
];

// ---------------------------------------------------------------------------
// Legacy curated team templates. The shipped world is now generated
// procedurally (see `clubs.rs`); these are retained only as test fixtures.
// ---------------------------------------------------------------------------

#[cfg(test)]
pub(super) struct TeamTemplate {
    pub name: &'static str,
    pub city: &'static str,
    pub country: &'static str,
    pub colors: (&'static str, &'static str),
    pub play_style: &'static str,
}

#[cfg(test)]
pub(super) const TEAM_TEMPLATES: &[TeamTemplate] = &[
    TeamTemplate {
        name: "London FC",
        city: "London",
        country: "England",
        colors: ("#dc2626", "#ffffff"),
        play_style: "Possession",
    },
    TeamTemplate {
        name: "Manchester City",
        city: "Manchester",
        country: "England",
        colors: ("#60a5fa", "#1e3a5f"),
        play_style: "Attacking",
    },
    TeamTemplate {
        name: "Liverpool Athletic",
        city: "Liverpool",
        country: "England",
        colors: ("#b91c1c", "#fbbf24"),
        play_style: "HighPress",
    },
    TeamTemplate {
        name: "Newcastle Town",
        city: "Newcastle",
        country: "England",
        colors: ("#000000", "#ffffff"),
        play_style: "Counter",
    },
    TeamTemplate {
        name: "Madrid Real",
        city: "Madrid",
        country: "Spain",
        colors: ("#ffffff", "#d4af37"),
        play_style: "Possession",
    },
    TeamTemplate {
        name: "Barcelona FC",
        city: "Barcelona",
        country: "Spain",
        colors: ("#9f1239", "#1d4ed8"),
        play_style: "Attacking",
    },
    TeamTemplate {
        name: "Munich Bayern",
        city: "Munich",
        country: "Germany",
        colors: ("#dc2626", "#1e3a5f"),
        play_style: "HighPress",
    },
    TeamTemplate {
        name: "Dortmund BV",
        city: "Dortmund",
        country: "Germany",
        colors: ("#eab308", "#000000"),
        play_style: "Counter",
    },
    TeamTemplate {
        name: "Paris Étoile",
        city: "Paris",
        country: "France",
        colors: ("#1e3a5f", "#dc2626"),
        play_style: "Attacking",
    },
    TeamTemplate {
        name: "Lyon Olympique",
        city: "Lyon",
        country: "France",
        colors: ("#1d4ed8", "#ffffff"),
        play_style: "Balanced",
    },
    TeamTemplate {
        name: "Milan Rossoneri",
        city: "Milan",
        country: "Italy",
        colors: ("#dc2626", "#000000"),
        play_style: "Defensive",
    },
    TeamTemplate {
        name: "Rome Gladiators",
        city: "Rome",
        country: "Italy",
        colors: ("#eab308", "#7c2d12"),
        play_style: "Counter",
    },
    TeamTemplate {
        name: "Amsterdam United",
        city: "Amsterdam",
        country: "Netherlands",
        colors: ("#dc2626", "#ffffff"),
        play_style: "Attacking",
    },
    TeamTemplate {
        name: "Lisbon Sporting",
        city: "Lisbon",
        country: "Portugal",
        colors: ("#16a34a", "#ffffff"),
        play_style: "Possession",
    },
    TeamTemplate {
        name: "Porto Dragões",
        city: "Porto",
        country: "Portugal",
        colors: ("#1d4ed8", "#ffffff"),
        play_style: "Defensive",
    },
    TeamTemplate {
        name: "Brussels Royal",
        city: "Brussels",
        country: "Belgium",
        colors: ("#7c3aed", "#fbbf24"),
        play_style: "Balanced",
    },
];
